### ISSUE TITLE
Solution hangs when fail

### ISSUE THREAD

**Issue by rickygodoy** [cloudspannerecosystem/machmeter#59] opened 2023-03-03 01:54 UTC
If something goes wrong with the execution, it hangs and won't exit even with cmd + C/cmd + d, had to `kill -9` it.

![image](https://user-images.githubusercontent.com/88061327/222611641-4cb0c314-6433-4b85-9aa1-3b7a88323946.png)

**Comment by manitgupta** [comment] 2023-03-06 05:23
Duplicate of #49

**Closed by manitgupta** 2023-03-06 05:23 UTC
